### ISSUE TITLE
deploy to maven repo

### ISSUE THREAD

**Issue by lecaros** [lenala/azure-gradle-plugins#10]
it would be nice to have this plugin available from public maven repo

**Comment by yoichiro** [comment]
I definitely agree. I tested the code set of the master branch, then I could confirm that basically this product worked normally. I think that most developers can use this as product level.

Also, I guess that there are many developers who are using Gradle to build Java softwares. Of course, I guess that there are many developers who are developing apps/services on Azure with Java/Kotlin/Scala and such programming languages. Currently, they can't use Gradle because they can't automate a deployment easily.

This product can bring an ability to automate a deployment to Azure for all products which are using Gradle. That is, many zure/Java programmers can have an option to use Gradle by this product. This is awesome. I hope that this product is published on the public Maven repository soon.

**Comment by srmds** [comment]
+1

**Comment by yoichiro** [comment]
@lenala What should we do so that we can say that we have enough preparations to publish this on public maven repo?

**Comment by yoichiro** [comment]
@lenala Great! You will be able to make many Gradle users so happy!

**Comment by lenala** [comment]
Plugins were released to gradle plugins repository.
Please note: groupId and artifactId have changed.

https://plugins.gradle.org/plugin/lenala.azure.azurewebapp
https://plugins.gradle.org/plugin/lenala.azure.azurefunctions

**Comment by yoichiro** [comment]
@lenala Thank you for the releasing and congrats! I intend to test the released version within a few days. I will file an issue, if I find any that.

**Comment by yoichiro** [comment]
@lenala Ok, I could confirm that the published Gradle plugin worked normally. The repository below was the project when I tested.

https://github.com/yoichiro/simple-action-azure-java-gradle

You can close this issue. Again, thank you for your work! :)

**Comment by lenala** [comment]
Thank you, closing!
